permalink: /:year-:month-:day/:title/

plugins: [jekyll-paginate]

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "TravelLeraLone"
email: "zhao_mengxin@sjtu.edu.cn"
description: "zzh的个人博客"
github_username:  "TravelLeraLone"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "rainyalley"




#url: "http://blog.rainyalley.com"
#imgrepo: "http://blog.rainyalley.com/static/img"


url: "https://travelleralone.github.io/"
imgrepo: "https://travelleralone.github.io/static/img"

